# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Auswilderungen
email: sophia.benz@bos-schweiz.ch
description: > # this means to ignore newlines until "baseurl:"
  Klappe auf, Affe raus!?
  Ganz so einfach ist es leider nicht…
baseurl: "/releases" # the subpath of your site, e.g. /blog
url: "https://b2bw.github.io" # the base hostname & protocol for your site
mailchimpURL: http://eepurl.com/cHtYxn

# Build settings
markdown: kramdown

# sass:
#   sass_dir: _sass
#   style: compressed


exclude:
  - package.json
  - node_modules
  - gulpfile.js
